language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer lint
  - php -l tests/examples/

matrix:
  fast_finish: true

notifications:
    on_success: never
    on_failure: always
